_target_: factr.task.BCTask
obs_dim: 27
ac_dim: 9
cam_indexes: []
n_cams: ${len:${task.cam_indexes}}
stiffness_classes: ${stiffness_classes}
eval_plot_max_steps: 400
eval_plot_prediction_stride: 25
eval_plot_num_samples: 10

# For Sweeping
eval_diversity_num_samples: 10
eval_diversity_max_batches: 2
sweep_target_min_diversity: 0.02
sweep_target_min_kl: 0.5
sweep_diversity_penalty: 2.0
sweep_kl_penalty: 0.05

train_buffer:
  _target_: factr.replay_buffer.RobobufReplayBufferLowdim
  buffer_path: ${buffer_path}
  n_test_ratio: 0.0
  mode: train
  use_internal_split: False
  ac_chunk: ${ac_chunk}
  obs_window: ${obs_window}
  obs_dim: ${task.obs_dim}
  pose_action_dim: ${task.ac_dim}
  action_index_offset: 0
  include_goals: False
  stiffness_classes: ${task.stiffness_classes}
  shuffle: True

test_buffer:
  _target_: factr.replay_buffer.RobobufReplayBufferLowdim
  buffer_path: ${test_buffer_path}
  n_test_ratio: 0.0
  mode: test
  use_internal_split: False
  ac_chunk: ${ac_chunk}
  obs_window: ${obs_window}
  obs_dim: ${task.obs_dim}
  pose_action_dim: ${task.ac_dim}
  action_index_offset: 0
  include_goals: False
  stiffness_classes: ${task.stiffness_classes}
  shuffle: False
