
input_path: /home/ferdinand/activeinference/factr/process_data/data_to_process/fourgoals_1/data
output_path: /home/ferdinand/activeinference/factr/process_data/processed_data/fourgoals_1_act

downsample: False
data_frequency: 50.0
target_downsampling_freq: 25.0


cameras_topics:
#   - /realsense/im

obs_topics:
  - /franka_robot_state_broadcaster/robot_state
  - /cartesian_impedance_controller/ee_velocity
  - /franka_robot_state_broadcaster/external_wrench_in_stiffness_frame
  - /cartesian_impedance_controller/tracking_error


# Normalization

# Explicit pose topic for grouped normalization (must be present in `obs_topics`)
pose_topic: /franka_robot_state_broadcaster/robot_state
 
pose_clip: 5.0           # set 0 to disable clipping (for observations and actions)
velocity_clip: 3.0       # set 0 to disable clipping
tracking_error_clip: 5.0 # set 0 to disable clipping (after Gaussian normalization)
wrench_clip: 5.0         # set 0 to disable clipping


action_config:
  # Commanded EE pose: 9D = [x,y,z] + 6D rotation representation
  /cartesian_impedance_controller/pose_command: 9

# Stiffness class extraction for observation:
# class=1 (low), class=2 (medium), class=3 (high)
stiffness_label_topic: /cartesian_impedance_gains
stiffness_label_key: stiffness
stiffness_norm_thresholds: [200.0, 1000.0]

goal_topic: 
  - /goal

# Optional train/test split at buffer creation time (episode-level random split).
# When enabled: writes two files in `output_path`, e.g. `buf_train.pkl` and `buf_test.pkl`.
train_test_split:
  enabled: true
  train_ratio: 0.90
  seed: 45
  train_buffer_name: buf_train
  test_buffer_name: buf_test
