
input_path: /home/ferdinand/factr/process_data/raw_data_train/20251107_60
output_path: /home/ferdinand/factr/process_data/training_data/20251107_60_25hz

median_filter_torque: False
median_filter_kernel_size_torque: 3
median_filter_position: False
median_filter_kernel_size_position: 7
filter_torque: False
cutoff_freq_torque: 10.0
filter_position: False
cutoff_freq_position: 10.0

downsample: True
data_frequency: 50.0
target_downsampling_freq: 25.0


cameras_topics:
  - /realsense/front/im

obs_topics:
# - /franka/right/obs_franka_torque
  - /franka_robot_state_broadcaster/external_joint_torques

action_config:
# /factr_teleop/right/cmd_franka_pos: 7
  /joint_impedance_command_controller/joint_trajectory: 7
