
input_path: /home/ferdinand/activeinference/factr/process_data/data_to_process/fourgoals_1/data
output_path: /home/ferdinand/activeinference/factr/process_data/training_data/fourgoals_1

median_filter_torque: False
median_filter_kernel_size_torque: 3
median_filter_position: False
median_filter_kernel_size_position: 7
filter_torque: False
cutoff_freq_torque: 10.0
filter_position: False
cutoff_freq_position: 12.0

downsample: False
data_frequency: 50.0
target_downsampling_freq: 25.0


cameras_topics:
#   - /realsense/im

obs_topics:
  - /franka_robot_state_broadcaster/robot_state
  - /cartesian_impedance_controller/ee_velocity
  - /franka_robot_state_broadcaster/external_wrench_in_stiffness_frame
  - /cartesian_impedance_controller/tracking_error

action_config:
  /cartesian_impedance_controller/pose_command: 9

goal_topic: 
  - /goal