
input_path: /home/ferdinand/factr_project/factr/process_data/raw_data_train/bld_both
output_path: /home/ferdinand/factr_project/factr/process_data/training_data/bld_both_52_filt

median_filter_torque: False
median_filter_kernel_size_torque: 3
median_filter_position: True
median_filter_kernel_size_position: 7
filter_torque: False
cutoff_freq_torque: 10.0
filter_position: True
cutoff_freq_position: 12.0

downsample: False
data_frequency: 50.0
target_downsampling_freq: 25.0


cameras_topics:
  - /realsense/front/im

obs_topics:
# - /franka/right/obs_franka_torque
  - /franka_robot_state_broadcaster/external_joint_torques

action_config:
# /factr_teleop/right/cmd_franka_pos: 7
  # /joint_impedance_command_controller/joint_trajectory: 7
  /joint_impedance_dynamic_gain_controller/joint_impedance_command: 7