
input_path: /home/ferdinand/activeinference/factr/process_data/data_to_process/fourgoals_1/data
output_path: /home/ferdinand/activeinference/factr/process_data/processed_data/fourgoals_1_norm2

downsample: False
data_frequency: 50.0
target_downsampling_freq: 25.0


cameras_topics:
#   - /realsense/im

obs_topics:
  - /franka_robot_state_broadcaster/robot_state
  - /cartesian_impedance_controller/ee_velocity
  - /franka_robot_state_broadcaster/external_wrench_in_stiffness_frame
  - /cartesian_impedance_controller/tracking_error


# Normalization

# Explicit pose topic for grouped normalization (must be present in `obs_topics`)
pose_topic: /franka_robot_state_broadcaster/robot_state
 
pose_clip: 5.0           # set 0 to disable clipping (for observations and actions)
velocity_clip: 3.0       # set 0 to disable clipping
tracking_error_clip: 5.0 # set 0 to disable clipping (after Gaussian normalization)
wrench_clip: 5.0         # set 0 to disable clipping


action_config:
  /cartesian_impedance_controller/pose_command: 9
  /cartesian_impedance_gains: 6

goal_topic: 
  - /goal
