
input_path: /home/ferdinand/factr/process_data/raw_data/20251024
output_path: /home/ferdinand/factr/process_data/processed_data/20251024

cameras_topics:
- /realsense/arm/im
obs_topics:
# - /franka/right/obs_franka_torque
# - /gripper/right/obs_gripper_pos
  - /franka/right/obs_franka_state
#  - /franka/right/obs_franka_torque
action_config:
  # /factr_teleop/right/cmd_franka_pos: 7
  /joint_impedance_command_controller/joint_trajectory: 7
  # /factr_teleop/right/cmd_gripper_pos: 1