# Copyright (c) Sudeep Dasari, 2023

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.


defaults:
  - agent: transformer_vit
  - task: franka
  - trainer: mae_cos_sched
  - _self_

hydra:
  run:
    dir: checkpoints/${exp_name}

rt: ${hydra:runtime.choices.agent/features}

exp_name: 1217mix_B64_pi5li_S45_lr25_2K_z128_β0005  #Batch, pixel or latent, Seed, lr, max_iteration, 関節の次元数, token_dim, dim_feedforward
batch_size: 64 
num_workers: 4 #データセットからデータを読み込む際に、並列で動かすプロセス（ワーカー）の数
lr: 0.00025
max_iterations: 20000
eval_freq: 500 #評価の頻度 (Evaluation Frequency) 。200回の学習ステップごとに、現在のモデルの性能をテストデータセットで評価
save_freq: 2000 #チェックポイント保存の頻度 (Save Frequency) 。2000回の学習ステップごとに、その時点でのモデルの重みをファイルに保存
schedule_freq: 1
devices: 2
seed: 45

buffer_path: ./buffer.pkl
ac_chunk: 30 #100
img_chunk: 1  # number of image timesteps to use (including current one)
train_transform: medium
test_transform: preproc

curriculum:
  space: pixel # pixel, latent
  operator: blur # blur, downsample
  scheduler: linear # no, const, linear, step, exp, cos
  start_scale: 5
  stop_scale: 0
  max_step: ${max_iterations}

wandb:
  name: ${exp_name}
  project: factr_1217_up_side
  group: bc
  debug: False #Falseに
  entity: a-otake2415-keio-university-global-page-org