# Copyright (c) Sudeep Dasari, 2023

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.


defaults:
  - agent: transformer_vit
  - task: franka
  - trainer: mae_cos_sched
  - _self_

hydra:
  run:
    dir: checkpoints/${exp_name}

rt: ${hydra:runtime.choices.agent/features}

exp_name: 20251024_25hz_60_btorque_traj_lowerbatch
batch_size: 16
num_workers: 4
lr: 0.0003
max_iterations: 15000 # ~9 epochs = (max_iterations * batch_size) / dataset_size (50 episodes × (600 raw steps / 2 downsample)=15,000)
eval_freq: 200
save_freq: 5000
schedule_freq: 1
devices: 2
seed: 42

buffer_path: ./buffer.pkl
ac_chunk: 25
img_chunk: 1  # number of image timesteps to use (including current one)
train_transform: medium
test_transform: preproc

curriculum:
  space: pixel # pixel, latent
  operator: blur # blur, downsample
  scheduler: linear # no, const, linear, step, exp, cos
  start_scale: 3
  stop_scale: 0
  max_step: ${max_iterations}

wandb:
  name: ${exp_name}
  project: factr
  group: bc
  debug: False
  entity: None