# Copyright (c) Sudeep Dasari, 2023

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

defaults:
  - agent: transformer_vit
  - task: franka
  - trainer: mae_cos_sched
  - _self_

hydra:
  run:
    dir: checkpoints_bld/${exp_name}

rt: ${hydra:runtime.choices.agent/features}

exp_base_name: bld_stiff_52_filt2
batch_size: 64
num_workers: 8
lr: 0.00022
max_iterations: 8000 # 20/50 epochs good maybe, (batch_size*max_iterations) / dataset_size , datasetsize=(54 episodes × (300 raw steps)=16,200)
eval_freq: 250
save_freq: 2000
schedule_freq: 1
devices: 1
seed: 52

suffix: _

# dataset_size = number_of_episodes * number_of_timesteps 
#              = 54 * 300 = 16200
#       epochs = (batch_size * max_iterations) / dataset_size
#              = (64 * 10000) / 16200 = 39.5

buffer_path: ./buffer.pkl
# buffer_path: /home/ferdinand/factr_project/factr/process_data/processed_data/20251024_train_60_filtered/buf.pkl
ac_chunk: 30
img_chunk: 1  # number of image timesteps to use (including current one)
train_transform: medium
test_transform: preproc

curriculum:
  space: pixel # pixel, latent
  operator: blur # blur, downsample
  scheduler: linear # no, const, linear, step, exp, cos
  start_scale: 5
  stop_scale: 0
  max_step: ${max_iterations}
  ratio: 0.667

use_indices: [0,1,2,3,4,5,6] 

exp_name: ${exp_base_name}_s${seed}_ac${ac_chunk}_b${batch_size}_lr${lr}_iter${max_iterations}${suffix}

wandb:
  name: ${exp_name}
  project: factr
  group: bc
  debug: False
  entity: None