defaults:
  - agent: transformer_lowdim
  - task: single_franka_lowdim
  - trainer: adamw_cos_lowdim
  - _self_

hydra:
  run:
    dir: /home/ferdinand/activeinference/factr/checkpoints/${exp_name}
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: "0"

buffer_path: /home/ferdinand/activeinference/factr/process_data/processed_data/fourgoals_1_act/buf_train.pkl
test_buffer_path: /home/ferdinand/activeinference/factr/process_data/processed_data/fourgoals_1_act/buf_test.pkl

exp_base_name: aiact_beta005_z8_fb0005_klb065
suffix: _
exp_name: ${exp_base_name}

batch_size: 128
num_workers: 8
lr: 0.00035
max_iterations: 10000
schedule_freq: 1
devices: 1
seed: 42
resume: false

ac_chunk: 30
obs_window: 8
train_transform: none
test_transform: none

train_log_freq: 50
eval_freq: 300
eval_freq_plot: 3000  # Must be multiple of eval_freq
save_freq: 2000

wandb:
  name: ${exp_name}
  project: aiact
  group: bc
  debug: False
  entity: None
