#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from factr.goal_inference import (  # noqa: E402
    build_display_goal_posterior_over_time,
    build_episode_goal_probability_figure,
    build_goal_likelihood_figure,
)


def parse_args():
    parser = argparse.ArgumentParser(description="Plot goal inference outputs (episode probability or horizon likelihood).")
    parser.add_argument(
        "--input-json",
        type=Path,
        required=True,
        help=(
            "Path to goal JSON generated by eval_single_episode_obs_pred_lowdim.py. "
            "Supports *_goal_probability_episode.json and *_goal_likelihoods_stepXXXX.json."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output figure path (.png). Default: <input-stem>_plot.png",
    )
    parser.add_argument(
        "--title-prefix",
        type=str,
        default="Goal Inference (4-way)",
        help="Optional title prefix.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    if not args.input_json.exists():
        raise FileNotFoundError(f"Input JSON not found: {args.input_json}")

    with open(args.input_json, "r") as f:
        payload = json.load(f)

    if "goal_probability" in payload:
        fig, goal_payload = build_episode_goal_probability_figure(
            goal_probabilities=np.asarray(payload["goal_probability"], dtype=np.float32),
            true_goal_labels=np.asarray(payload["true_goal_label"], dtype=np.int64),
            pred_goal_labels=np.asarray(payload.get("pred_goal_label", []), dtype=np.int64) if "pred_goal_label" in payload else None,
            time_index=np.asarray(payload.get("time_index", []), dtype=np.int64) if "time_index" in payload else None,
            title_prefix=str(args.title_prefix),
        )
        print(f"Goal probability check | max|sum(p)-1|={goal_payload['max_sum_error']:.3e} mean|sum(p)-1|={goal_payload['mean_sum_error']:.3e}")
    else:
        loglik_t = np.asarray(payload["log_likelihood_per_timestep"], dtype=np.float32)
        obs_dim = int(payload.get("obs_dim", payload.get("predict_obs_dim", payload.get("obs_target_dim", 21))))
        posterior_t = build_display_goal_posterior_over_time(
            log_likelihood_over_time=loglik_t,
            obs_dim=obs_dim,
            temperature=5.0,
            include_uniform_prior=True,
        )
        true_goal = payload.get("true_goal_label", None)
        pred_goal = payload.get("pred_goal_label", None)

        fig = build_goal_likelihood_figure(
            log_likelihood_over_time=loglik_t,
            posterior_over_time=posterior_t,
            true_goal_label=true_goal,
            pred_goal_label=pred_goal,
            title_prefix=str(args.title_prefix),
        )

    if args.output is None:
        out_path = args.input_json.with_name(f"{args.input_json.stem}_plot.png")
    else:
        out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


if __name__ == "__main__":
    main()
